language: node_js
sudo: required
before_script:
  - npm install -g bower
  - bower install
  - chmod -R +x scripts
script: ./scripts/build.sh
node_js: '6'
after_success:
  - ./scripts/create-release.sh
dist: trusty